name: Checks

on:
  pull_request:
    
jobs:
  local-sim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install bs4 requests cloudscraper python-dotenv
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Node dependencies
        run: npm install
      - name: Create .env
        run: |
          echo "DATABASE_PATH=file:$(pwd)/database.db" >> .env
          echo "ROOT_URL=http://localhost:5501/" >> .env
          echo "GITHUB_CLIENT_ID=dummy" >> .env
          echo "GITHUB_CLIENT_SECRET=dummy" >> .env
          echo "DISCORD_CLIENT_ID=dummy" >> .env
          echo "DISCORD_CLIENT_SECRET=dummy" >> .env
          echo "GOOGLE_CLIENT_ID=dummy" >> .env
          echo "GOOGLE_CLIENT_SECRET=dummy" >> .env
          echo "QOJ_USER=dummy" >> .env
          echo "QOJ_PASS=dummy" >> .env
      - name: Setup Prisma and DB
        run: |
          npx prisma migrate deploy
          npx prisma generate
      - name: Populate problems
        run: npm run syncProblems
      - name: Populate contests
        run: npm run syncContests
      - name: Test server startup
        run: |
          timeout 5s npm run dev || true